hash-format = "sha256"

[[files]]
file = "1.txt"
hash = "05490592240c746b4c3e192e1ba7e05d778850c9a91dfd09a1218d8c0c38084c"

[[files]]
file = "add.py"
hash = "d97b6236cf99206366181eb98dc3758c1e3ce94dbde60be0fd23556e84c82bb7"

[[files]]
file = "mods/almanac.pw.toml"
hash = "6317bd1e6013059a52574d7002e744cd1d662ba345d019d75e37d384fd6060b0"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "006b24892ead1f3b1319727bcd41c32db322e3eb61956825387c3788bfd9e168"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "a26507b8d655a13e1ec6901e620a3d8fbd0840b9c239b2fb8a32e1b43800e557"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "0c8a62a213ee50629ec25fbddc988cbdeae36d906df8d5e8924dfd172d116166"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "30eff8901d5955ab62196e335926047f6c00278fd95eb04b4e4b7122a8c31f15"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "4532263b7e8c2ff26a5bb2303a25200509c58686baaefe7b88cc5cd8e3efa258"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "5eade022da85f205b7f13e0610fb1a9bd8f06d99d584ff5d6bd708e846a87f48"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b628817fa969d8fa2554534553eaa8a54f40e09c63a6dfd5cf1b4e5d99fa3d17"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "2ea660633b80f4d21fb03008958df7a596afe3dfbe9b737dfe12929ed1ef92d0"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "896ec8a8f0524aaf58d311a316c137ce8934154732c4c3425c3b571fcc86c7ce"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4737f39234f9cf1faf075ea80228ce38982e56cc9df8a277aff3a0e10e4005ad"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "15385164e2cd07cce7493a10d6d87df5c7bce587a866613126be3b54b6b28fc7"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "0179a3dc5e3edae377999da95a982679bcda21dd4ed863e53c4358db71346835"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "765c845fe7e63a5d1ce2a4a4f31dac08c8f6a58dc61f73f2556287f72628e6d8"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "02b241514a81b37b21c080ca9cc5f3815a4ceafc4424f4feb8d5073cfafa61e9"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "6ec7fc70c84dc7f7f4578a85480264d82336d64ac0d8c95c0fcc55d350f64ab7"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "52355f7f314b3208a1a51ed5ca0ad94986eb22ab174465fbe36b92a3c5b3c7fe"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "b2a6e13d1fefa68ffe13304f74f5e3173ea5d24d30dd84ed32b564e6da88f31f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "9326ad2077287f079ab68743e5d597af75bf7f166927079fcfa7545fc86c4cd5"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "cb8962724f1752a9dbe170cb76127fa6abe5eb24c88598a1d720591d6f92411a"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "816b719eb96d91e39a44ead15dbe176951484a1915c52f05eed9100dfadf280d"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "08784382ad844087012493864fcc24a68530dc285d8145cf0ff87e347935c618"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6ee58cdcf7aa8fff1ab9436bdfc50bed51fa785094052e21dfb2446072e11f7a"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "9d92444a5e9a5704c6dc035e9670e0df982c1e23a9368374fce3a5b1236daed6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5aec219adc9536b4554033a54c563a027297a319836ef5e8dd3078fda8ac2e32"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2831d2be7f52107b8cb23145f8812485c7ee12107a4eabf47d39d5b5d778cf04"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "e248d23f43fa50e6014902db890fa6546c3763858da8192862bfcc3070bf56be"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "25336c1f30011e78325573d0d6f4319c3b49340148313b5dbf31c579e7fb8085"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "7c80079f8907c29bba18bd6bfd1eeeade4be790a39ff0e358d6e72441dd8108f"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "33cf6c7885bb2a0d2e95467b546565cad5bd2714e2e53601ab8011b6910eac26"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "324a179d92186b13ec7059000e01739e1e627fd08eade9b59962e968d6292f6b"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3fc5381d3b12edccba3108a99830466358ed44c8fa55d12bbd2f9d84687e50e2"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "0f83be0761e0014686517c20f2850242152dd7a26e87088d869028bc40a8a125"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "ec0e252c91555b61ba6132207c925d95e85e26ca16f8082e47b367860a70cc88"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "fe3e6bdf7ee24ca65e68ffe7110f0eb6c9c27bfcb94b190f63063aba4c7ff2bd"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4fb1efcf4c3c16eac7382421134d6472130884b9e4dd2a57fe0eb62c47203173"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "d81fd8c747b4cbb57a31817584df701d266d3e59b5d82bb408020803e1ed6ee9"
metafile = true

[[files]]
file = "mods/leaves-be-gone.pw.toml"
hash = "37421d14755957856ddafed04020b2b23f902f6f4c410fb5bdfc956959f99fba"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3d21f13970fdd89524a8e0520c8a6ec774a6fe4b37b49d295e956e17dc9ffadc"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "62b5f6133f799c95d48314eef3e353b8689477f075e9f604a2566de03d593563"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "ac064da8e05f3c215e850f34a78004e0742575c3cef3165040cb5cd5e6a40e99"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "a5306de623d85768f0f5660ecf15182bcdce376a993ba5a224fb0e8e542c2ddb"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "daec0d362957def2195281d781f0d4937f95e162fd0304a4965edc79de1a62e1"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "91e27eb5ae869f5cb1b5911a51f7eb7884a71bfa6701c3f6a2b7a2ce1e02e187"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "fd154e3e5956017a5fdff17b150e91a3ba607897d4b01382a9194a197a3153ee"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "837915662c472b9672e4a5bed43343a37917fb947b3b86c929bdc73024497fc3"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "ac5e7ba0771228a52f0e8c26f9125959039b4d4761bc346b56a5221c721de46a"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "041187f58c7c416c8e5044907238e1896b0f21dbf05ab04c04803c3feaa7e78c"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "f42ebaf193a5b9571fd69afd92ad3d6e0b73535ab97e385314801b81b6325767"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "ba5ff18e27aa4a5ef3cc763c0f17178c57a916b183035678715ff0fa3f6fee6b"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5ce2f4ca8c22e9bd1def9f669d7ce1b4f61ed7fcbea57c8678f97239f8f8d94c"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "515b1bbd8e92bb4ad03a9cd63a28c499f4ebb13fab4716b3e486eb5dd0f3d36c"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "90883a27b0256572844f1ea7a4ae6d92d8d4af55d4bc351f41049c5b66848f6c"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "30b93a2927883fd0395fbd7dfd32a09d2099a1c3a861c104743e81f8a2fbda09"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "75fbe6959e6e824431f0d5a437691b1b0c507c4572373bb116c16bb182e55407"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "828e4ac952b00d33bc27873fbae3aa561ad4aa812ae6ab6b47950bb76bfad52e"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2d8e0917d75a40bc302b3f63135a025b26f3b3032e25e92b8f7a1c5d28e720f0"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "c27c70a1fdb36fc974c98b6c678de8d1c2fd8e3705d90ad5089b82421933bf00"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "ca74da88eec22117d3ba4e20041154749fbc12b8034762a3e0c9070b8e2f0fe3"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "08c75262a7504024ca9db500ea0ae73a4be8f41e34189015d92d0e2a4280f564"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a1eff7b33a54586b6989c7bfd89992f9d315f1c656b7596649d9af7017c6af7b"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "025c644cfcbdb32ceaa85029588101c71089888a5dd6b83d2b54da285718efa5"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
hash = "63273748b9bbadcfefedc5bc5fddfe367d637abd094c1f931b7ab9e720dd58b2"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "77a658a9d9cec5037136b95c42d1dff26dbf4010f17ecb2116bebf69178a03ba"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "88a52b0be49e854235bfbf15c68c855d6a42a00eb2700744286cced41936ff41"
metafile = true

[[files]]
file = "mods/ryoamiclights.pw.toml"
hash = "76c3cb745800fae4ceee5155ea53d0a31e001f6a0e4fb56be82c269649e32ca5"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "2428fa3db05e2f3efd181e9a1b37c3a9a293c62b9ab82abc846c311345d8ef59"
metafile = true

[[files]]
file = "mods/smarter-farmers-farmers-replant.pw.toml"
hash = "bd947e3ce3578234db935ad9a24c2e9c00c4d686bfb521e2a200b4cac483a7e1"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "f46a28713596f69fcbbd90870844a2e3e6ffc6000ae3ceb6164fc39223bd6175"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "1cf0acce03896f82c4ea323ac64087c58133ca1338d2e5a28754e8f6846ab8b6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "196310c8f35ff43df20828f78aeaa532c62faa036c58a913ca9d419cfa39c2d4"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "c527a3d8f6c2c3dce7b7a8afb2b94676298f15867a19698b20d2c14905b24ca0"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "a5b7358eb8b4795a3ab36872a8c2a0e1c1bf6a518a168f2eb10b695a35cb64b5"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "7b7108d879e1e1c141b24d0d8fa268a6bbcd5c227875d156fcc62c3beec55f63"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "d912d9e221bd014cecf575f4389dee37238258ef69ad27ba64c021487441da46"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "97135836e2392a011aff2801fffbbeb314c292c433af580ece5838d713fc8f57"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "2f35ba95e1265777b6b2411f769af2670e45141c646a2bb0cb90f18772deb981"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "95940b5fc72e8df82ab3adb72b43d10a37e6d926fbb37c405c9fe50bda27a991"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "7dd536d000999274472fa6762bcd49deaeb301fd0889c32723c1129db2400561"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "c360a4aef0ce719d385529002ba157a731d572b73cefb573c763d71d54039078"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "a837a0028b1e1bbb6c4e5d31bf3cb04d6f6dccae90fc93df46f9a60a8b2c53c1"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "cf708ff146f867df2153b3f27482e80769c7032b10037e4a752d31fbb5668eaf"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "8bc20a4cf22bdd4406a64126647cfe3c704e80a3197031c9154032905a276705"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "f23d28e95b21a9655e615390a560bc66f3cb87610ac38cd9d849129d0600a766"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "b2af03e504a1827f2f6fc09597e7d51f4ecd64ab1ebb329a9eb9ffb98372673a"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "0b5eb310353cce6e94ffb0558cb713815b63328e6e96f804f147b5291c237a98"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "7e89ac9ea56f87a811a289d474b8ab4fe46d7a235b4c6ef4767e5099967d656e"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "d201155cab7c2a2cf940d91f240be769ac12046c2fc6a0774e225a8e51423ed0"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "6e2beb8e290b0fda881553e2accf050853ae02c3a2d07edd877a8c35e461547a"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "60f6bbb4c9edc73c1fbe871e485949dd9a337fb6a95990543935f59619955d38"
metafile = true
