hash-format = "sha256"

[[files]]
file = "1.txt"
hash = "321c5ed6129c58cef1735ef81e167d0b1eaed4947ce3c04e4240f4f03fd0e045"

[[files]]
file = "add.py"
hash = "d97b6236cf99206366181eb98dc3758c1e3ce94dbde60be0fd23556e84c82bb7"

[[files]]
file = "mods/animatica.pw.toml"
hash = "e94fd2f80b6029f19fb0c68d5bbf443a21645af0d668c5a544e3b3f23508fb61"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b8c29dac6fb7c1cf18ca53b7a96c6c4854307999b77a751e803bdd9650a125e0"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "333dfa2b93c688ce5f9f685f77cb62e5df8b9c8d21a2c4dd4eb9232aa85dccff"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "444dc7b515acd2e5a5b399c78fe89758f43bfe962a453472ad18a50193eae8b6"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "64a244469b7ce7be7e6ceabedd69d17e573a0b92d6e29c661fc6c490afa965d8"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "ec2c437fe50a3f8ea6077215974ba9f769cb94eb29432156cbbe43137a74013f"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "87e9490344614e88f3d83be8a9ab18237b2ae60b12aafee85b0870501db31132"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "4accbc204fe2a7dd1680dd665f5266afe023369f0adf3a0e79fdc24db326acf9"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "5944ed5a779d142aea9ccd8c466a20fa3d9233a29f2be1e5ae54fc15f5edd57e"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "8f611c3cf31eb5f5b3395b99414d794029192d556fd8dfc4b49a097a67134ccf"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "d1239fb872fc0765dcedf2a0e46dc61674729acb834511bb175ef17760ac8040"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "c9102ad224c1496927d326707ee2cd2a2cfd6f278f05e23a19aa45395306daf6"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d7651af3a8996488151254f0379fd7f1613edeaf7eac48bdeff447eeaf411965"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "7eefb0f3d1b793f7dc57ee7cf368d055c9b1bf3556f61179f38f1c49c163c1bd"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "9c8b6d8e1a13a4f7edd081c1ab561c51069d6315a67c217a88fafcd1ddfb17a8"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "83ac3e7f70eb567845286596a8baad96b73ef3c2ee1fa378375df7a13aad7c11"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "d987a241a56c9e3fde315ca942c8240911b51c98d7d5bd1f089c25ddb8b6cca1"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "9c58c6f6299c9ab982847248be076b6840df69ce6b647a2a18e81d9a1cbeaf19"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d9d01681616a8bdb45bbdd0a053b87153bbb77a5ef997325be0b3dc10b7f8979"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "6c154d18505c366b2117c2cfa06ea66a7f3e1a441456c3e20f195cb446f8103b"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "43b7544c0a49c9368caf33a1529a720c6fadb17f7d07db6a8e952b514b5a862c"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "866baeb7e9917b92825ddbcf4d113648a6662b5214e078b29c327ff97d0e2774"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6cd55df8041a48cb7f5f95ea4520f5ed59064e71ff9dab8b0e02bb922b68c9cb"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "435267c3230ba1439f50fa32c3ed3993a4123f870681451aa95acdde5d52622e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "0d438cc5a467aae6a9aa439a4547f990dfbaa4dc4e7bf5dbabf6d6e839411e83"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "9ff690ee32105d52a646a76f48371ccbe1958aff274511ca71fb44099ebc7107"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "ad302d4bc503de96528b917401fa6f4652cc03bd2e506912d0e5157ecabe9cbd"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "e94cfc8b72a467d63c5d7593a433edaf698a3792e0c9b95274751ba6d8435288"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "f87252f70d1fa65de868bde3162d7a41e136447f44ce6683473f48026b093393"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "a0b2b689e7e6eb10cd342da48dd605cfbe09d782790a42089f31835a54e37b1a"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "421b6b05164e623dc65e0e4133fc484fb3b87b26b040ad4b2ffb239491d8bb2d"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "6247a7c55d598c185c0a78c6c2c10eac870b64bc4ab58039e98b9715b90b8e9b"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "9ed765da71f977af16c71b3ff56356dea5a149d9626277e4d4868941f8efa1b0"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "1dbd3b2969118cf3bf47efd9eac2838abb815efce4d33ea47091f20b42ebfd24"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "4384bc790b955c7329be45a0f5a140f7159598718076e8c06d425f91cefbba87"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3209dc8a6aa57006e67478802f9c8074ec4d4a3d3bb62b818b8ee71f9276184f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "4a7d1e46795d2d83b18db85d8dbc63740a1d337e12d2b9e550378de59f2b23ab"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "83164a6af3923e28cadf9d404f059bf74aa4f0842fc1ca0f6e7cf1e686044875"
metafile = true

[[files]]
file = "mods/ryoamiclights.pw.toml"
hash = "9fa71aa8e78fc08ad70d99029bff202bdf4757035f13fd6f4a00ea090f9e7ed6"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "058f62395b41a3b18121bcd961320cc8fd8460a34a5ccb4f07552e42ff19df4a"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8ad07191dfdea31249b4416a390c1cdf1d4ff1938cf9f8a617f98f7a08c5356c"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "bf3a50b4962319fdc9bcdb9b56aa5af1d674a16740c36f5732cb8fe91aafb46f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "98553c2d49ef3a888954f24b7c49fe3442c01fd4fc1f1ed52c5898ed29d29d3b"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "53b00436579bd2ea920ef8ae8b1464cb4744dbfd21055d8a3f4768019b78e5bc"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "74906aa6f2f33b0391252d50b1d446d2ad2df4d6ca1026b941e90cc579a0692b"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d2d5a9c835661b4f6f718fd057f03594b87aa49d1bcd9711af8553e51ea4a6fb"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "d77dfc3bf13ca53b19b15564800167012835deab25e6a97a09b4a699bd5843e8"
metafile = true
