hash-format = "sha256"

[[files]]
file = "1.txt"
hash = "05490592240c746b4c3e192e1ba7e05d778850c9a91dfd09a1218d8c0c38084c"

[[files]]
file = "add.py"
hash = "d97b6236cf99206366181eb98dc3758c1e3ce94dbde60be0fd23556e84c82bb7"

[[files]]
file = "mods/animatica.pw.toml"
hash = "a26507b8d655a13e1ec6901e620a3d8fbd0840b9c239b2fb8a32e1b43800e557"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "0c8a62a213ee50629ec25fbddc988cbdeae36d906df8d5e8924dfd172d116166"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "4532263b7e8c2ff26a5bb2303a25200509c58686baaefe7b88cc5cd8e3efa258"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "5eade022da85f205b7f13e0610fb1a9bd8f06d99d584ff5d6bd708e846a87f48"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "b628817fa969d8fa2554534553eaa8a54f40e09c63a6dfd5cf1b4e5d99fa3d17"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "2ea660633b80f4d21fb03008958df7a596afe3dfbe9b737dfe12929ed1ef92d0"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "896ec8a8f0524aaf58d311a316c137ce8934154732c4c3425c3b571fcc86c7ce"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4737f39234f9cf1faf075ea80228ce38982e56cc9df8a277aff3a0e10e4005ad"
metafile = true

[[files]]
file = "mods/connectivity.pw.toml"
hash = "0179a3dc5e3edae377999da95a982679bcda21dd4ed863e53c4358db71346835"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "765c845fe7e63a5d1ce2a4a4f31dac08c8f6a58dc61f73f2556287f72628e6d8"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "02b241514a81b37b21c080ca9cc5f3815a4ceafc4424f4feb8d5073cfafa61e9"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "52355f7f314b3208a1a51ed5ca0ad94986eb22ab174465fbe36b92a3c5b3c7fe"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "b2a6e13d1fefa68ffe13304f74f5e3173ea5d24d30dd84ed32b564e6da88f31f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "9326ad2077287f079ab68743e5d597af75bf7f166927079fcfa7545fc86c4cd5"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "cb8962724f1752a9dbe170cb76127fa6abe5eb24c88598a1d720591d6f92411a"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "816b719eb96d91e39a44ead15dbe176951484a1915c52f05eed9100dfadf280d"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "08784382ad844087012493864fcc24a68530dc285d8145cf0ff87e347935c618"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6ee58cdcf7aa8fff1ab9436bdfc50bed51fa785094052e21dfb2446072e11f7a"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "9d92444a5e9a5704c6dc035e9670e0df982c1e23a9368374fce3a5b1236daed6"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5aec219adc9536b4554033a54c563a027297a319836ef5e8dd3078fda8ac2e32"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2831d2be7f52107b8cb23145f8812485c7ee12107a4eabf47d39d5b5d778cf04"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "e248d23f43fa50e6014902db890fa6546c3763858da8192862bfcc3070bf56be"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "25336c1f30011e78325573d0d6f4319c3b49340148313b5dbf31c579e7fb8085"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "7c80079f8907c29bba18bd6bfd1eeeade4be790a39ff0e358d6e72441dd8108f"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "33cf6c7885bb2a0d2e95467b546565cad5bd2714e2e53601ab8011b6910eac26"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "324a179d92186b13ec7059000e01739e1e627fd08eade9b59962e968d6292f6b"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "3fc5381d3b12edccba3108a99830466358ed44c8fa55d12bbd2f9d84687e50e2"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "ec0e252c91555b61ba6132207c925d95e85e26ca16f8082e47b367860a70cc88"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "fe3e6bdf7ee24ca65e68ffe7110f0eb6c9c27bfcb94b190f63063aba4c7ff2bd"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "4fb1efcf4c3c16eac7382421134d6472130884b9e4dd2a57fe0eb62c47203173"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "d81fd8c747b4cbb57a31817584df701d266d3e59b5d82bb408020803e1ed6ee9"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3d21f13970fdd89524a8e0520c8a6ec774a6fe4b37b49d295e956e17dc9ffadc"
metafile = true

[[files]]
file = "mods/macos-input-fixes.pw.toml"
hash = "ac064da8e05f3c215e850f34a78004e0742575c3cef3165040cb5cd5e6a40e99"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "a5306de623d85768f0f5660ecf15182bcdce376a993ba5a224fb0e8e542c2ddb"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "daec0d362957def2195281d781f0d4937f95e162fd0304a4965edc79de1a62e1"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "0a8e6a58962ba40f696a44cb2d02355490bc831b49509f8083e3e7bc89b40052"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "91e27eb5ae869f5cb1b5911a51f7eb7884a71bfa6701c3f6a2b7a2ce1e02e187"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "fd154e3e5956017a5fdff17b150e91a3ba607897d4b01382a9194a197a3153ee"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "837915662c472b9672e4a5bed43343a37917fb947b3b86c929bdc73024497fc3"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "041187f58c7c416c8e5044907238e1896b0f21dbf05ab04c04803c3feaa7e78c"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
hash = "f42ebaf193a5b9571fd69afd92ad3d6e0b73535ab97e385314801b81b6325767"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "5ce2f4ca8c22e9bd1def9f669d7ce1b4f61ed7fcbea57c8678f97239f8f8d94c"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "515b1bbd8e92bb4ad03a9cd63a28c499f4ebb13fab4716b3e486eb5dd0f3d36c"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
hash = "90883a27b0256572844f1ea7a4ae6d92d8d4af55d4bc351f41049c5b66848f6c"
metafile = true

[[files]]
file = "mods/nuit-interop.pw.toml"
hash = "30b93a2927883fd0395fbd7dfd32a09d2099a1c3a861c104743e81f8a2fbda09"
metafile = true

[[files]]
file = "mods/nuit.pw.toml"
hash = "75fbe6959e6e824431f0d5a437691b1b0c507c4572373bb116c16bb182e55407"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "828e4ac952b00d33bc27873fbae3aa561ad4aa812ae6ab6b47950bb76bfad52e"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "2d8e0917d75a40bc302b3f63135a025b26f3b3032e25e92b8f7a1c5d28e720f0"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "c27c70a1fdb36fc974c98b6c678de8d1c2fd8e3705d90ad5089b82421933bf00"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "ca74da88eec22117d3ba4e20041154749fbc12b8034762a3e0c9070b8e2f0fe3"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "08c75262a7504024ca9db500ea0ae73a4be8f41e34189015d92d0e2a4280f564"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "025c644cfcbdb32ceaa85029588101c71089888a5dd6b83d2b54da285718efa5"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "88a52b0be49e854235bfbf15c68c855d6a42a00eb2700744286cced41936ff41"
metafile = true

[[files]]
file = "mods/ryoamiclights.pw.toml"
hash = "76c3cb745800fae4ceee5155ea53d0a31e001f6a0e4fb56be82c269649e32ca5"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "2428fa3db05e2f3efd181e9a1b37c3a9a293c62b9ab82abc846c311345d8ef59"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "f46a28713596f69fcbbd90870844a2e3e6ffc6000ae3ceb6164fc39223bd6175"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "1cf0acce03896f82c4ea323ac64087c58133ca1338d2e5a28754e8f6846ab8b6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "196310c8f35ff43df20828f78aeaa532c62faa036c58a913ca9d419cfa39c2d4"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "c527a3d8f6c2c3dce7b7a8afb2b94676298f15867a19698b20d2c14905b24ca0"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "a5b7358eb8b4795a3ab36872a8c2a0e1c1bf6a518a168f2eb10b695a35cb64b5"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "d912d9e221bd014cecf575f4389dee37238258ef69ad27ba64c021487441da46"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "97135836e2392a011aff2801fffbbeb314c292c433af580ece5838d713fc8f57"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "2f35ba95e1265777b6b2411f769af2670e45141c646a2bb0cb90f18772deb981"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "6e2beb8e290b0fda881553e2accf050853ae02c3a2d07edd877a8c35e461547a"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "60f6bbb4c9edc73c1fbe871e485949dd9a337fb6a95990543935f59619955d38"
metafile = true
